# -*- coding: utf-8 -*-
"""DESAFIO_CS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1127Yt3HTlGbiGotvaKHQVOqdIX0EHfD9
"""

# Importando as bibliotecas necessárias
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Lendo o arquivo json
source = pd.read_json("https://api.github.com/search/repositories?q=language:python&sort=starts")

# Observando a quantidade de estrelas dadas a cada repositório = popularidade
# NOTA: A popularidade (stargazers_count) vai mudando em real-time, de acordo às estrelas recebidas por cada repositório
fields = ["id", "stargazers_count"]
df = pd.json_normalize(source["items"])
df[fields]

# Criando uma primeira função para o Gráfico que mostra os 6 respositórios mais populares que usam Python como linguagem nos seus códigos......

def barplot(y):
  
  # Ordenando os respositórios de maior a menor popularidade...
  popularidade_ordenada = df["id"]
  popularidade_ordenada.sort_index()
  
  # Definindo os parâmetros do gráfico...
  sns.set(style = "darkgrid")
  chart = sns.barplot(x = "id", y = y, data = df, order = popularidade_ordenada)
  chart.set_xticklabels(chart.get_xticklabels(), rotation=45)
  
  # Salvando o gráfico em formato png com 300 dpi...
  plt.savefig("popularidade_repositorios_github.png", format = "png", dpi = 300, bbox_inches = 'tight')
  
  # Salvando o gráfico em formato svg...
  plt.savefig("popularidade_repositorios_github.svg", format="svg")

# Plotando e mostrando o gráfico de barras contendo os respositórios que usam Python como linguagem nos seus códigos...
plt.figure(figsize = (20,8))
barplot(y = "stargazers_count")
plt.title("Gráfico de barras da popularidade dos repositórios que usam a linguagem Python nos seus códigos depositados no GitHub")
plt.ylabel("Quantidade de estrelas recebidas por cada ID")
plt.xlabel("ID de cada repositório")
plt.show()

"""**NOTA:**

Para saber mais sobre a diferença entre os formatos png e svg, leitura recomendada:
[Diferença entre png e svg](https://www.pagecloud.com/blog/web-images-png-vs-jpg-vs-gif-vs-svg)
"""

df2 = df.head(6)
df2[fields]

# Criando uma segunda função para o Gráfico que mostra os 6 respositórios mais populares que usam Python como linguagem nos seus códigos......

def barplot2(y):
  
  # Ordenando os respositórios de maior a menor popularidade...
  popularidade_ordenada = df2["id"]
  popularidade_ordenada.sort_index()
  
  # Definindo os parâmetros do gráfico...
  sns.set(style = "darkgrid")
  chart = sns.barplot(x = "id", y = "stargazers_count", data = df2, order = popularidade_ordenada)
  chart.set_xticklabels(chart.get_xticklabels(), rotation=45)
  # Salvando o gráfico em formato png com 300 dpi...
  plt.savefig("popularidade_6_primeiros_repositorios_github.png", format = "png", dpi = 300, bbox_inches = 'tight')
  # Salvando o gráfico em formato svg...
  plt.savefig("popularidade_6_primeiros_repositorios_github.svg", format="svg")

# Plotando e mostrando o gráfico de barras contendo os 6 respositórios mais populares que usam Python como linguagem nos seus códigos...
plt.figure(figsize = (10,6))
barplot2(y = "stargazers_count")
plt.title("Gráfico de barras dos primeiros 6 repositórios mais populares que usam a linguagem Python nos seus códigos depositados no GitHub")
plt.ylabel("Estrelas recebidas pelos 6 repositórios mais populares")
plt.xlabel("ID dos primeiros 6 repositórios")
plt.show()